### ISSUE TITLE
Fatal Exceptions During RC Startup.  Is this normal?

### ISSUE THREAD

**Issue by caryden** [FIRST-Tech-Challenge/FtcRobotController#401]
Using AS Dolphin and fully updated Control Hub, when the RC starts the log has several fatal exceptions.  After this, everything seems to work, but it is discomforting.  Is this normal?

'''
FATAL EXCEPTION: main
                                                                                                    Process: com.qualcomm.ftcrobotcontroller, PID: 1402
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/qualcomm/robotcore/hardware/LegacyModule;
                                                                                                    	at org.firstinspires.ftc.onbotjava.handlers.file.NewFile.<clinit>(NewFile.java:98)
                                                                                                    	at org.firstinspires.ftc.onbotjava.OnBotJavaProgrammingMode.register(OnBotJavaProgrammingMode.java:117)
                                                                                                    	at org.firstinspires.ftc.robotserver.internal.programmingmode.ProgrammingModeManager.setState(ProgrammingModeManager.java:132)
                                                                                                    	at org.firstinspires.ftc.robotcontroller.internal.FtcRobotControllerActivity.onServiceBind(FtcRobotControllerActivity.java:675)
                                                                                                    	at org.firstinspires.ftc.robotcontroller.internal.FtcRobotControllerActivity$1.onServiceConnected(FtcRobotControllerActivity.java:199)
                                                                                                    	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1453)
                                                                                                    	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1481)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:755)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                    	at android.os.Looper.loop(Looper.java:154)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.robotcore.hardware.LegacyModule" on path: DexPathList[[zip file "/data/app/com.qualcomm.ftcrobotcontroller-2/base.apk"],nativeLibraryDirectories=[/data/app/com.qualcomm.ftcrobotcontroller-2/lib/arm64, /data/app/com.qualcomm.ftcrobotcontroller-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at org.firstinspires.ftc.onbotjava.handlers.file.NewFile.<clinit>(NewFile.java:98) 
                                                                                                    	at org.firstinspires.ftc.onbotjava.OnBotJavaProgrammingMode.register(OnBotJavaProgrammingMode.java:117) 
                                                                                                    	at org.firstinspires.ftc.robotserver.internal.programmingmode.ProgrammingModeManager.setState(ProgrammingModeManager.java:132) 
                                                                                                    	at org.firstinspires.ftc.robotcontroller.internal.FtcRobotControllerActivity.onServiceBind(FtcRobotControllerActivity.java:675) 
                                                                                                    	at org.firstinspires.ftc.robotcontroller.internal.FtcRobotControllerActivity$1.onServiceConnected(FtcRobotControllerActivity.java:199) 
                                                                                                    	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1453) 
                                                                                                    	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1481) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:755) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                                    	at android.os.Looper.loop(Looper.java:154) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795) 
'''
Also failed resource loads:
'''
failed to add asset path /data/app/com.qualcomm.ftcrobotcontroller-2/base.apk
2022-10-12 09:47:35.886   551-551   ResourcesManager        pid-551                              E  failed to add asset path /data/app/com.qualcomm.ftcrobotcontroller-2/base.apk
2022-10-12 09:47:35.886   551-551   ResourcesManager        pid-551                              E  failed to add asset path /data/app/com.qualcomm.ftcrobotcontroller-2/base.apk
2022-10-12 09:47:35.887   551-551   ResourcesManager        pid-551                              E  failed to add asset path /data/app/com.qualcomm.ftcrobotcontroller-2/base.apk
2022-10-12 09:47:35.887   551-551   ResourcesManager        pid-551                              E  failed to add asset path /data/app/com.qualcomm.ftcrobotcontroller-2/base.apk
'''

and... 
'''
java.lang.ClassNotFoundException: com.journeyapps.barcodescanner.ScanContract
2022-10-12 09:47:36.249  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at java.lang.Class.classForName(Native Method)
2022-10-12 09:47:36.251  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at java.lang.Class.forName(Class.java:400)
2022-10-12 09:47:36.254  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at org.firstinspires.ftc.robotcore.internal.opmode.ClassManager.classNamesToClasses(ClassManager.java:215)
2022-10-12 09:47:36.256  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at org.firstinspires.ftc.robotcore.internal.opmode.ClassManager.processAllClasses(ClassManager.java:258)
2022-10-12 09:47:36.257  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at com.qualcomm.ftccommon.ClassManagerFactory.processAllClasses(ClassManagerFactory.java:94)
2022-10-12 09:47:36.259  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at org.firstinspires.ftc.robotcontroller.internal.FtcRobotControllerActivity.onCreate(FtcRobotControllerActivity.java:356)
2022-10-12 09:47:36.259  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at android.app.Activity.performCreate(Activity.java:6709)
2022-10-12 09:47:36.260  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
2022-10-12 09:47:36.260  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
2022-10-12 09:47:36.261  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
2022-10-12 09:47:36.261  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at android.app.ActivityThread.-wrap12(ActivityThread.java)
2022-10-12 09:47:36.262  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
2022-10-12 09:47:36.262  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at android.os.Handler.dispatchMessage(Handler.java:102)
2022-10-12 09:47:36.262  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at android.os.Looper.loop(Looper.java:154)
2022-10-12 09:47:36.263  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at android.app.ActivityThread.main(ActivityThread.java:6121)
2022-10-12 09:47:36.263  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at java.lang.reflect.Method.invoke(Native Method)
2022-10-12 09:47:36.263  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
2022-10-12 09:47:36.264  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:795)
2022-10-12 09:47:36.265  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.journeyapps.barcodescanner.ScanContract" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
2022-10-12 09:47:36.266  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
2022-10-12 09:47:36.266  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
2022-10-12 09:47:36.267  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2022-10-12 09:47:36.267  3739-3739  ClassManager            com.qualcomm.ftcrobotcontroller      E  	... 18 more
'''

And there are several others.

**Comment by qwertychouskie** [comment]
According to https://ftctechnh.github.io/ftc_app/doc/javadoc/index.html the LegacyModule code is for the Modern Robotics Core Legacy Module, which allowed legacy hardware back from the NXT/Samantha Module days to be used with the Modern Robotics system.  None of that has been relevant for many years, it looks like some code just wasn't properly deleted.  Should be a simple fix, hopefully they get it properly removed for 8.2 (though it's not hurting anything currently).  Not sure what's up with the others, they don't look fatal though.
